<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>

<body>

</body>
<script>
  /*
  try {
    new Promise((resolve, reject) => {
      throw new Error('promise error'); // // Uncaught (in promise) Error: promise error
    })
  } catch (err) {
    console.log('In catch:', err); 
  } finally {
    console.log('In finally'); // 无论 try / catch 的结果如何都会执行。
  }
  */

  // /*
    try {
      new Promise((resolve, reject) => {
          // reject('promise reject err');
          throw new Error('promise error');
      }).then(
        (res) => {
          console.log(res);
          throw res;
        },(err) => {
          console.log('In promise error:',err); // In promise error: Error: promise error
      })
      throw new Error('第一个try 内发出的err')
    } catch (err) {
        console.log('In catch:',err); // Uncaught (in promise) Error: promise error
    } finally {
        console.log('In finally'); // 无论 try / catch 的结果如何都会执行。
    }
  // */

</script>

</html>